SELECT * 
FROM inc_5000;


-- Identify the top 3 companies and industries with the highest revenue
SELECT 
	"name",
	industry,
	revenue
FROM inc_5000
ORDER BY revenue DESC
LIMIT 3;


-- Identify the number of years the company with the highest revenue have been listed
SELECT 
	"name",
	industry,
	revenue,
	yrs_on_list
FROM inc_5000
ORDER BY revenue DESC
LIMIT 3;


-- Identify the number of workers in these industry
SELECT 
	"name", 
	industry,
	revenue,
	workers
FROM inc_5000
ORDER BY revenue DESC
LIMIT 3;


-- Identify companies and industries with the lowest revenue, limit to 3
SELECT 
	"name",
	industry,
	revenue
FROM inc_5000
ORDER BY revenue ASC
LIMIT 3;


-- Identify the number of workers in these industry
SELECT 
	"name",
	industry,
	revenue,
	workers
FROM inc_5000
ORDER BY revenue ASC
LIMIT 3;


-- Identify the companies and industries with the highest growth rate
SELECT 
	"name",
	industry,
	revenue,
	"growth_%"
FROM inc_5000
ORDER BY "growth_%" DESC
LIMIT 3;


-- Identify the companies and industries with the lowest growth rate, limit to 3
SELECT 
	"name",
	industry,
	revenue,
	"growth_%"
FROM inc_5000
ORDER BY "growth_%" ASC
LIMIT 3;


-- Check the number of years the companies with the lowest growth rate have been listed
SELECT 
	"name",
	industry,
	revenue,
	"growth_%"
	yrs_on_list
FROM inc_5000
ORDER BY "growth_%" ASC
LIMIT 3;


-- identify the number of workers, year founded and revenue for Vivayic, HNM Systems, and Naval Sysytems
SELECT 
	"name",
	workers,
	founded
FROM inc_5000
WHERE "name" IN ('Vivayic', 'HNM Systems', 'Naval Systems');


-- Identify the top 3 industry with the highest number of workers. ignore null values
SELECT 
	"name",
	industry,
	workers
FROM inc_5000
WHERE workers NOTNULL
ORDER BY workers DESC
LIMIT 3;


-- Identify the industry with the lowest number of workers
SELECT
	"name"
	industry,
	revenue,
	workers
FROM inc_5000
ORDER BY workers ASC
LIMIT 1;


-- List of comapnies with name begining from 'Fr'
SELECT 
	"name",
	"state",
	city
FROM inc_5000
WHERE "name" LIKE 'Fr%';


-- Identify all the companies in the food and beverage industry
SELECT 
	"name"
FROM inc_5000 
WHERE industry LIKE 'Food & Beverage';


-- Identify companies that do not have chicken as part of their name
SELECT
	"name",
	"state",
	revenue,
	"growth_%"
FROM inc_5000
WHERE industry LIKE 'Food & Beverage' AND "name" NOT LIKE '%Chicken%';


-- Identify the list of companies that are under the Advertising & Marketing industry, revenue, workers and year founded
SELECT 
	"name",
	revenue,
	workers,
	founded
FROM inc_5000
WHERE industry IN ('Advertising & Marketing');


-- Identify the company that has been on the list the longest, the industry and revenue
SELECT 
	yrs_on_list,
	"name",
	industry,
	revenue
FROM inc_5000
ORDER BY yrs_on_list DESC
LIMIT 1;


-- Sum the revenue generated from each industry
SELECT 
	industry,
	sum(revenue) as "Industry_Revenue"
FROM inc_5000
GROUP BY industry
ORDER BY "Industry_Revenue" DESC;


-- Calculate the sum of workers from each industry
SELECT 
	industry, 
	sum(workers) as "Total Workers"
FROM inc_5000
GROUP BY industry
ORDER BY "Total Workers" DESC;


-- Identify all the companies under the health industry
SELECT 
	"name",
	industry,
	revenue
FROM inc_5000
WHERE industry  IN ('Health')
ORDER BY revenue ASC;


-- Identify the company with the highest evenue from the health industry
SELECT 
	"name",
	revenue
FROM inc_5000
WHERE industry IN ('Health')
ORDER BY revenue DESC
LIMIT 1;


-- Calculate the percentage of the revenue made by Prime Therapeutics against the total revenue generated from the health industry
SELECT 
	name,
	ROUND(revenue *100/ (SELECT sum(revenue)
			  FROM inc_5000
			  WHERE industry IN ('Health')),2) As Percentage
FROM inc_5000
WHERE "name" IN ('Prime Therapeutics');


-- Calculate the percentage of revenue generated by each industry from the total revenue generated
SELECT 
	industry, 
	ROUND(sum(revenue)*100/(SELECT sum(revenue)
				FROM inc_5000),2) As Percentage
FROM inc_5000
GROUP BY industry
ORDER BY Percentage DESC;

				
-- Identifying the most represented and the lease represented industry
SELECT
	industry,
	count("name") As "Count"
FROM inc_5000
GROUP BY industry
ORDER BY "Count" DESC;
	

-- Identifying trends from state
SELECT
	"state",
	sum(revenue) "Revenue"
FROM inc_5000
GROUP BY "state"
ORDER BY "Revenue" DESC;


SELECT
	"state",
	count("name") "Name"
FROM inc_5000
GROUP BY "state"
ORDER BY "Name" DESC;


-- Industry with the average highest growth rate
SELECT
	industry,
	ROUND(avg("growth_%"),2) AS "Growth Rate"
FROM inc_5000
GROUP BY industry
ORDER BY "Growth Rate" DESC;

